# -*- coding: utf-8 -*-
"""huggingface

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLNB0RLJbKh2ecESwrplgWF8KxsN96Cq
"""

pip install transformers torch

from transformers import pipeline

# Load pretrained sentiment analysis model
sentiment_model = pipeline("sentiment-analysis")

# Test sentence
text = "Excellent product"

# Get prediction
result = sentiment_model(text)

print("Text:", text)
print("Prediction:", result[0]['label'])
print("Confidence Score:", result[0]['score'])